spring:
  datasource:
    url: jdbc:mariadb://localhost:7779/ibg?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ibg
    password: ssafyB101!
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create

    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 7777
  servlet:
    context-path: /ibg

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace